/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SafariPersonaIndexRouteImport } from './routes/safari-persona/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafariPersonaIndexRoute = SafariPersonaIndexRouteImport.update({
  id: '/safari-persona/',
  path: '/safari-persona/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/safari-persona': typeof SafariPersonaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/safari-persona': typeof SafariPersonaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/safari-persona/': typeof SafariPersonaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/safari-persona'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/safari-persona'
  id: '__root__' | '/' | '/safari-persona/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SafariPersonaIndexRoute: typeof SafariPersonaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safari-persona/': {
      id: '/safari-persona/'
      path: '/safari-persona'
      fullPath: '/safari-persona'
      preLoaderRoute: typeof SafariPersonaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SafariPersonaIndexRoute: SafariPersonaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
